version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing nx...
      - yarn global add nx
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building frontend...
      - nx build frontend
      - echo Packaging Lambda function...
      - cd libs/backend/lambdas/src/yahoo
      - zip -r ../../../../../yahoo.zip index.mjs # Package the Lambda function
      - cd ../../../../..
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Deploying lambda function...
      - aws lambda update-function-code --function-name yahoo_finance --zip-file fileb://yahoo.zip --region us-east-1
      - echo Deployment completed on `date`

artifacts:
  files: '**/*'
  base-directory: dist/apps/frontend
