AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  yahoo

  Sample SAM Template for yahoo

Resources:
  YahooFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: libs/backend/lambdas/src/yahoo/
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
        YahooFinance:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /yahoo_finance
            Method: post
